name: CI

# TODO-CI: Re-enable GitHub Actions when project structure stabilizes
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

on:
  push:
    branches: [nonexistent]
  pull_request:
    branches: [nonexistent]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          cache: true
      - run: pnpm install
      - run: pnpm test
      - run: pnpm test:a11y
      - run: pnpm build
